export { default as AdminRouter } from "./admin";
export { default as TotdRouter } from "./totd";
export { default as ImagesRouter } from "./images";
export { default as AuthenticationRouter } from "./authentication";
export { default as LeaderboardRouter } from "./leaderboard";
export { default as ServiceRouter } from "./services";
export { default as ChallengeRouter } from "./challenge";
export { default as CotdRouter } from "./cotd";
export { default as PlayerRouter } from "./player";
